<!DOCTYPE HTML>
<!DOCTYPE html>
<html>
<head>
	<title>Login Admin</title>
	 <link rel="stylesheet" href="<?=base_url()?>assets/style/Login.css">
</head>
<body>
	<div class="body">
		
		<div class="container"> 
			<div class="logo">
			<img src="<?=base_url()?>assets/image/ika.png">
			</div> <br><br><br>
			<div class="form-style-3">
			<form>
				<label for="field1">
					<span> Username <span class="required">*</span></span>
					<input type="text" class="input-field" name="field1" value="">
				</label>
				<label for="field3">
					<span> Password <span class="required">*</span></span>
					<input type="Password" class="input-field" name="field3" value="">
				<label>
					<span>&nbsp;</span>
					<br> <br> <br>
					<input type="submit" value="Login">
				</label>
			</form>
		</div>

</div>
</div>
</body>
</html>