<!DOCTYPE HTML>
<!DOCTYPE html>
<html>
<head>
	<title>Login Admin</title>
	 <link rel="stylesheet" href="<?=base_url()?>assets/style/Login.css">
</head>
<body>
	<div class="body">
		
		<div class="konten">
        <div class="kepala">
            <div class="lock"></div>
            <div class="judul">
                <img src="<?=base_url()?>assets/image/ika.png">
            </div>
        </div>
        <div class="artikel">
            <H3>Login Admin</H3>
            <form action="#" method="post">
                <div class="grup">
                    <input type="text" placeholder="Username">
                </div>
                <div class="grup">
                    <input type="password" placeholder="Password">
                </div>
                <br>
                <div class="grup">
                    <input type="submit" value="Login">
                </div>
            </form>
        </div>
    </div>

</div>
</div>
</body>
</html>